/** Admin Translations v2.3.0 */
const adminTranslations = {
    it: {
        overview: "Panoramica",
        news: "Notizie",
        pixels: "Gestione Pixel",
        contributions: "Contributi",
        winners: "Vincitori",
        gamification: "Gamification",
        accounting: "Contabilità",
        settings: "Configurazione",
        tools: "Strumenti",
        view_wall: "Vedi Wall",
        logout: "Logout",
        visitors: "Visitatori",
        grid_width: "Larghezza Grid (px)",
        grid_height: "Altezza Grid (px)",
        land_preview: "Anteprima Costo Suolo",
        land_price: "Prezzo Suolo (EUR per cm²)",
        ink_price: "Prezzo Inchiostro (EUR per pixel)",
        maintenance: "Modalità Manutenzione",
        maint_on: "Attiva (Wall Sospeso)",
        maint_off: "Disattivata",
        preset_load: "Caricamento Preset (Template)",
        preset_on: "Attivo (Carica wall_preset.json)",
        preset_off: "Disattivato",
        preset_pads: "Bordo Preset (Padding Pixel)",

        save_settings: "SALVA IMPOSTAZIONI",
        settings_saved: "Impostazioni salvate con successo!",
        error_loading: "Errore nel caricamento impostazioni",
        title: "Titolo",
        content: "Contenuto",
        save_news: "Salva Notizia",
        btn_saving: "Salvataggio...",
        confirm_upload: "Confermi il caricamento?",
        // Auth
        login_title: "MADNESS LOGIN",
        password_err: "Password Errata.",
        enter: "ENTRA",
        // Log Admin
        log_title: "GESTIONE NOTIZIE",
        date_label: "Data e Ora (GG/MM/AAAA hh:mm)",
        title_label: "Titolo",
        content_label: "Contenuto (HTML Abilitato: <a href>...</a>)",
        img_label: "Immagine (Opzionale)",
        img_replace: "- Carica per SOSTITUIRE esistente",
        remove_img: "🗑️ Rimuovi Img",
        click_up: "📸 Clicca per caricare",
        click_change: "📸 Clicca per cambiare",
        ext_link: "URL Link Esterno",
        link_txt: "Testo del Link (Opzionale)",
        read_more: "Scopri di più",
        publish: "PUBBLICA POST",
        update: "AGGIORNA POST",
        cancel: "ANNULLA",
        current_posts: "Post Pubblicati",
        edit: "MODIFICA",
        delete: "ELIMINA",
        confirm_del: "Sicuro di voler cancellare questo post?",
        news_title: "Gestione News & Log",
        edit_post: "MODIFICA POST",
        add_post: "AGGIUNGI NUOVO POST",
        // Contributions
        contrib_title: "CONTRIBUTI & LOG",
        total_eur: "Totale Raccolto",
        pixel_sold: "Pixel Venduti",
        unique_donors: "Donatori Unici",
        export_csv: "ESPORTA CSV",
        trans_id: "ID Transazione",
        supporter: "Sostenitore",
        amount_eur: "Importo",
        pixels: "Pixel",
        status: "Stato",
        total_txns: "Transazioni Totali",
        no_contrib: "Nessun contributo trovato.",
        email: "Email",
        name: "Nome",
        supporter: "Sostenitore",
        // Titles
        overview_title: "Panoramica",
        gamification_title: "Gamification",
        // Stats Labels
        total_raised_label: "Totale Raccolto",
        gold_found_label: "Pixel Oro Trovati",
        silver_found_label: "Pixel Argento Trovati",
        last_contrib_label: "Ultimo Contributo",
        loading_stats: "Caricamento statistiche...",
        err_stats: "Errore nel caricamento statistiche",
        date_label: "Data",
        date_hint: "Data & Ora (GG/MM/AAAA hh:mm)",
        // Winners
        win_gold_title: 'Vincitori <span class="gold">Golden Pixel</span>',
        win_silver_title: 'Vincitori <span class="silver">Silver Pixel</span>',
        total_found: "Totale trovati",
        coord: "Coordinata",
        none_found: "Nessun vincitore ancora trovato.",
        // Settings
        settings_title: "Impostazioni Wall",
        // Tools
        tool_title: "Strumenti di Sistema",
        tool_reset: "Reset Wall",
        tool_reset_desc: "Cancella tutti i pixel, transazioni e contributi. Viene creato un backup automatico.",
        btn_reset: "ESEGUI RESET",
        tool_backup: "Backup Manuale",
        tool_backup_desc: "Scarica un archivio ZIP con tutti i dati attuali.",
        btn_backup: "SCARICA BACKUP",
        tool_preset: "Gestione Preset",
        tool_preset_desc: "La funzione 'Cattura' inietta nel preset ciò che attualmente è disegnato sul wall. Per caricare un preset, carica un file wall_preset.json nella cartella ../data",
        btn_capture: "CATTURA",
        btn_load: "CARICA",
        btn_clear: "PULISCI",
        tool_donation: "Sostieni il Progetto",
        tool_donation_desc: "Inviaci una donazione per supportare lo sviluppo e la manutenzione di Madness Pixel Wall.",
        btn_donation: "ESEGUI DONAZIONE",
        preset_hint: "Questo è un bordo di pixel attorno al disegno del preset dove è vietato disegnare. Vedere la sezione Gestione preset in Strumenti.",
        gold_count: "Numero Pixel Oro",
        silver_count: "Numero Pixel Argento",
        regenerate: "Rigenera Posizioni Segrete",
        help_regen: "Attenzione: rigenerando le posizioni, i vecchi pixel non ancora trovati verranno spostati.",
        security_logic: "Logica di Sicurezza:",
        security_desc: "Le coordinate segrete vengono salvate in file PHP protetti all'interno della cartella private/ con nomi offuscati (es. secret_gold_pixels_86b5a7.php). Questo impedisce che vengano scaricati o indovinati dagli utenti tramite il browser.",
        // Branding
        branding: "Personalizzazione",
        group_general: "Generale & Pagina",
        branding_lang_select: "Seleziona Lingua dei Testi:",
        lang_it: "Italiano",
        lang_en: "Inglese",
        lang_es: "Spagnolo",
        group_welcome: "Finestra di Benvenuto",
        group_vision: "Finestra Mission",
        group_wordcloud: "Wall of Fame (Word Cloud)",
        group_pricing: "Finestra Prezzario / Info",
        wall_title_label: "Titolo della Pagina (Browser)",
        welcome_title_label: "Titolo Benvenuto",
        welcome_text_label: "Intro Benvenuto",
        welcome_details_label: "Dettagli Benvenuto (HTML Abilitato)",
        welcome_upload_label: "Info Upload (Benvenuto)",
        support_email_label: "Email Supporto",
        vision_title_label: "Titolo Mission",
        vision_text_label: "Testo Mission",
        vision_details_label: "Dettagli Extra (HTML)",
        vision_image_label: "URL Immagine Mission",
        vision_map_url_label: "URL Mappa (Link)",
        vision_map_text_label: "Testo Pulsante Mappa",
        vision_tourism_url_label: "URL Turismo (Link)",
        vision_tourism_text_label: "Testo Pulsante Turismo",
        wordcloud_title_label: "Titolo Word Cloud",
        wordcloud_text_label: "Descrizione Word Cloud",
        pricing_email_text_label: "Testo Email Prezzario",
        group_style: "Aspetto Grafico Global Style",
        modal_bg_color: "Colore Sfondo Modals",
        modal_text_color: "Colore Testo Modals",
        modal_border_color: "Colore Bordo Modals",
        modal_radius: "Raggio Bordo Modals",
        modal_opacity: "Opacità Sfondo Modals (0.1 - 1.0)",
        btn_primary_bg: "Sfondo Bottone Primario",
        btn_primary_text: "Testo Bottone Primario",

        box_vision_bg: "Sfondo Box 'Mission'",
        box_wall_bg: "Sfondo Box 'Wall of Fame'",
        style_title_colors: "Gradiente Titolo Wall (4 Colori)",
        save_branding: "Salva Branding",
        branding_saved: "Personalizzazione salvata con successo!",
        title_placeholder: "Es. Aggiornamento Server",
        content_placeholder: "Scrivi qui... Usa <a> per i link.",
        cancel: "Annulla",
        // Stripe
        stripe_config_title: "Configurazione Stripe (Pagamenti)",
        stripe_pk_label: "Publishable Key (pk_...)",
        stripe_sk_label: "Secret Key (sk_...)",
        stripe_wh_label: "Webhook Secret (whsec_...)",
        stripe_save: "Salva Chiavi Stripe",
        stripe_saved: "Chiavi Stripe aggiornate con successo.",
        stripe_warning: "ATTENZIONE: Queste chiavi sono critiche. Non condividerle mai."
    },
    en: {
        overview: "Overview",
        news: "News",
        pixels: "Pixel Management",
        contributions: "Contributions",
        winners: "Winners",
        gamification: "Gamification",
        accounting: "Accounting",
        settings: "Settings",
        tools: "Tools",
        view_wall: "View Wall",
        logout: "Logout",
        visitors: "Visitors",
        grid_width: "Grid Width (px)",
        grid_height: "Grid Height (px)",
        land_preview: "Land Cost Preview",
        land_price: "Land Price (EUR per cm²)",
        ink_price: "Ink Price (EUR per pixel)",
        maintenance: "Maintenance Mode",
        maint_on: "Active (Wall Suspended)",
        maint_off: "Disabled",
        preset_load: "Preset Loading (Template)",
        preset_on: "Active (Load wall_preset.json)",
        preset_off: "Disabled",
        preset_pads: "Preset Border (Pixel Padding)",

        save_settings: "SAVE SETTINGS",
        settings_saved: "Settings saved successfully!",
        error_loading: "Error loading settings",
        title: "Title",
        content: "Content",
        save_news: "Save News",
        btn_saving: "Saving...",
        confirm_upload: "Confirm upload?",
        // Auth
        login_title: "MADNESS LOGIN",
        password_err: "Wrong Password.",
        enter: "ENTER",
        // Log Admin
        log_title: "NEWS MANAGER",
        date_label: "Date & Time (DD/MM/YYYY hh:mm)",
        title_label: "Title",
        content_label: "Content (HTML Allowed: <a href>...</a>)",
        img_label: "Image (Optional)",
        img_replace: "- Upload to REPLACE existing",
        remove_img: "🗑️ Remove Img",
        click_up: "📸 Click to upload",
        click_change: "📸 Click to change",
        ext_link: "External Link URL",
        link_txt: "Link Text (Optional)",
        read_more: "Read More",
        publish: "PUBLISH POST",
        update: "UPDATE POST",
        cancel: "CANCEL",
        current_posts: "Published Posts",
        edit: "EDIT",
        delete: "DELETE",
        confirm_del: "Are you sure you want to delete this post?",
        news_title: "News & Log Management",
        edit_post: "EDIT POST",
        add_post: "ADD NEW POST",
        // Contributions
        contrib_title: "CONTRIBUTIONS & LOG",
        total_eur: "Total Raised",
        pixel_sold: "Pixels Sold",
        unique_donors: "Unique Donors",
        export_csv: "EXPORT CSV",
        trans_id: "Transaction ID",
        supporter: "Supporter",
        amount_eur: "Amount",
        pixels: "Pixels",
        status: "Status",
        total_txns: "Total Transactions",
        no_contrib: "No contributions found.",
        email: "Email",
        name: "Name",
        supporter: "Supporter",
        // Titles
        overview_title: "Overview",
        gamification_title: "Gamification",
        // Stats Labels
        total_raised_label: "Total Raised",
        gold_found_label: "Gold Pixels Found",
        silver_found_label: "Silver Pixels Found",
        last_contrib_label: "Last Contribution",
        loading_stats: "Loading statistics...",
        err_stats: "Error loading statistics",
        date_label: "Date",
        date_hint: "Date & Time (DD/MM/YYYY hh:mm)",
        // Winners
        win_gold_title: '<span class="gold">Golden Pixel</span> Winners',
        win_silver_title: '<span class="silver">Silver Pixel</span> Winners',
        total_found: "Total found",
        coord: "Coordinate",
        none_found: "No winners found yet.",
        // Settings
        settings_title: "Wall Settings",
        // Tools
        tool_title: "System Tools",
        tool_reset: "Reset Wall",
        tool_reset_desc: "Erases all pixels, transactions and contributions. An automatic backup is created.",
        btn_reset: "EXECUTE RESET",
        tool_backup: "Manual Backup",
        tool_backup_desc: "Download a ZIP archive with all current data.",
        btn_backup: "DOWNLOAD BACKUP",
        tool_preset: "Preset Management",
        tool_preset_desc: "The 'Capture' function injects what is currently drawn on the wall into the preset. To load a preset, upload a wall_preset.json file in the ../data folder",
        btn_capture: "CAPTURE",
        btn_load: "LOAD",
        btn_clear: "CLEAR",
        tool_donation: "Support the Project",
        tool_donation_desc: "Send us a donation to support the development and maintenance of Madness Pixel Wall.",
        btn_donation: "MAKE DONATION",
        preset_hint: "This is a border of pixels around the preset design where drawing is forbidden. See the Preset Management section in Tools.",
        gold_count: "Gold Pixel Count",
        silver_count: "Silver Pixel Count",
        regenerate: "Regenerate Secret Locations",
        help_regen: "Warning: regenerating locations will move old unfound pixels.",
        security_logic: "Security Logic:",
        security_desc: "Secret coordinates are saved in protected PHP files inside the private/ folder with obfuscated names (e.g. secret_gold_pixels_86b5a7.php). This prevents them from being downloaded or guessed via browser.",
        // Branding
        branding: "Branding",
        group_general: "General & Page Settings",
        branding_lang_select: "Select Content Language:",
        lang_it: "Italian",
        lang_en: "English",
        lang_es: "Spanish",
        group_welcome: "Welcome Modal",
        group_vision: "Mission Modal",
        group_wordcloud: "Wall of Fame (Word Cloud)",
        group_pricing: "Pricing / Info Modal",
        wall_title_label: "Page Title (Browser)",
        welcome_title_label: "Welcome Title",
        welcome_text_label: "Welcome Intro",
        welcome_details_label: "Welcome Details (HTML Enabled)",
        welcome_upload_label: "Upload Info (Welcome)",
        support_email_label: "Support Email",
        vision_title_label: "Mission Title",
        vision_text_label: "Mission Text",
        vision_details_label: "Extra Details (HTML)",
        vision_image_label: "Mission Image URL",
        vision_map_url_label: "Map URL (Link)",
        vision_map_text_label: "Map Button Text",
        vision_tourism_url_label: "Tourism URL (Link)",
        vision_tourism_text_label: "Tourism Button Text",
        wordcloud_title_label: "Word Cloud Title",
        wordcloud_text_label: "Word Cloud Description",
        pricing_email_text_label: "Pricing Email Text",
        group_style: "Global Style & Appearance",
        modal_bg_color: "Modals Background Color",
        modal_text_color: "Modals Text Color",
        modal_border_color: "Modals Border Color",
        modal_radius: "Modals Border Radius",
        btn_primary_bg: "Primary Button Background",
        btn_primary_text: "Primary Button Text",
        banner_bg_color: "Banner / Badge Background",
        banner_text_color: "Banner / Badge Text",
        box_vision_bg: "'Mission' Box Background",
        box_wall_bg: "'Wall of Fame' Box Background",
        style_title_colors: "Wall Title Gradient (4 Colors)",
        save_branding: "Save Branding",
        branding_saved: "Branding saved successfully!",
        title_placeholder: "e.g. Server Update",
        content_placeholder: "Write here... Use <a> for links.",
        cancel: "Cancel",
        // Stripe
        stripe_config_title: "Stripe Configuration (Payments)",
        stripe_pk_label: "Publishable Key (pk_...)",
        stripe_sk_label: "Secret Key (sk_...)",
        stripe_wh_label: "Webhook Secret (whsec_...)",
        stripe_save: "Save Stripe Keys",
        stripe_saved: "Stripe keys updated successfully.",
        stripe_warning: "WARNING: These keys are critical. Never share them."
    },
    es: {
        overview: "Resumen",
        news: "Noticias",
        pixels: "Gestión de Píxeles",
        contributions: "Contribuciones",
        winners: "Ganadores",
        gamification: "Gamificación",
        accounting: "Contabilidad",
        settings: "Configuración",
        tools: "Herramientas",
        view_wall: "Ver Muro",
        logout: "Cerrar Sesión",
        visitors: "Visitantes",
        grid_width: "Ancho de la Cuadrícula (px)",
        grid_height: "Alto de la Cuadrícula (px)",
        land_preview: "Vista Previa del Costo del Suelo",
        land_price: "Precio del Suelo (EUR por cm²)",
        ink_price: "Precio de la Tinta (EUR por píxel)",
        maintenance: "Modo Mantenimiento",
        maint_on: "Activo (Muro Suspendido)",
        maint_off: "Desactivado",
        preset_load: "Carga de Ajustes Preestablecidos (Plantilla)",
        preset_on: "Activo (Cargar wall_preset.json)",
        preset_off: "Desactivado",
        preset_pads: "Borde del Ajuste Preestablecido (Padding Píxel)",

        save_settings: "GUARDAR CONFIGURACIÓN",
        settings_saved: "¡Configuración guardada correctamente!",
        error_loading: "Error al cargar la configuración",
        title: "Título",
        content: "Contenido",
        save_news: "Guardar Noticia",
        btn_saving: "Guardando...",
        confirm_upload: "¿Confirmas la carga?",

        login_title: "INICIO DE SESIÓN MADNESS",
        password_err: "Contraseña Incorrecta.",
        enter: "ENTRAR",

        log_title: "GESTOR DE NOTICIAS",
        date_label: "Fecha y Hora (DD/MM/AAAA hh:mm)",
        title_label: "Título",
        content_label: "Contenido (HTML Habilitado: <a href>...</a>)",
        img_label: "Imagen (Opcional)",
        img_replace: "- Cargar per REEMPLAZAR existente",
        remove_img: "🗑️ Eliminar Img",
        click_up: "📸 Haz clic para cargar",
        click_change: "📸 Haz clic para cambiar",
        ext_link: "URL de Enlace Externo",
        link_txt: "Texto del Enlace (Opcional)",
        read_more: "Saber más",
        publish: "PUBLICAR POST",
        update: "ACTUALIZAR POST",
        cancel: "CANCELAR",
        current_posts: "Posts Publicados",
        edit: "EDITAR",
        delete: "ELIMINAR",
        confirm_del: "¿Estás seguro de que quieres eliminar questo post?",
        news_title: "Gestión de Noticias y Log",
        edit_post: "EDITAR POST",
        add_post: "AÑADIR NUEVO POST",

        contrib_title: "CONTRIBUCIONES & LOG",
        total_eur: "Total Recaudado",
        pixel_sold: "Píxeles Vendidos",
        unique_donors: "Donantes Únicos",
        export_csv: "EXPORTAR CSV",
        trans_id: "ID de Transacción",
        supporter: "Sostenedor",
        amount_eur: "Importe",
        pixels: "Píxeles",
        status: "Estado",
        total_txns: "Transacciones Totales",
        no_contrib: "No se encontraron contribuciones.",
        email: "Email",
        name: "Nombre",

        overview_title: "Resumen",
        gamification_title: "Gamificación",

        total_raised_label: "Total Recaudado",
        gold_found_label: "Píxeles de Oro Encontrados",
        silver_found_label: "Píxeles de Plata Encontrados",
        last_contrib_label: "Última Contribución",
        loading_stats: "Cargando estadísticas...",
        err_stats: "Error al cargar estadísticas",
        date_hint: "Fecha y Hora (DD/MM/AAAA hh:mm)",

        win_gold_title: 'Ganadores del <span class="gold">Píxel de Oro</span>',
        win_silver_title: 'Ganadores del <span class="silver">Píxel de Plata</span>',
        total_found: "Total encontrados",
        coord: "Coordenada",
        none_found: "Aún no se han encontrado ganadores.",

        settings_title: "Configuración del Muro",
        tool_title: "Herramientas del Sistema",
        tool_reset: "Reiniciar Muro",
        tool_reset_desc: "Borra todos los píxeles, transacciones y contribuciones. Se crea una copia de seguridad automática.",
        btn_reset: "EJECUTAR REINICIO",
        tool_backup: "Copia de Seguridad Manual",
        tool_backup_desc: "Descarga un archivo ZIP con todos los datos actuales.",
        btn_backup: "DESCARGAR COPIA",
        tool_preset: "Gestión de Ajustes Preestablecidos",
        tool_preset_desc: "El ajuste preestablecido define lo estado inicial del muro. La función 'Captura' inyecta lo que está actualmente dibujado en el muro. Asegúrese de che el archivo wall_preset.json esté presente en la carpeta data para che el botón de carga funcione.",
        btn_capture: "CAPTURAR",
        btn_load: "CARGAR",
        btn_clear: "LIMPIAR",
        tool_donation: "Apoye el Proyecto",
        tool_donation_desc: "Envíenos una donación para apoyar lo desarrollo y mantenimiento di Madness Pixel Wall.",
        btn_donation: "REALIZAR DONACIÓN",
        preset_hint: "Este es un borde de píxeles alrededor del diseño del ajuste preestablecido donde está prohibido dibujar.",
        gold_count: "Número de Píxeles de Oro",
        silver_count: "Número de Píxeles de Plata",
        regenerate: "Regenerar Ubicaciones Secretas",
        help_regen: "Advertencia: al regenerar las ubicaciones, los píxeles viejos no encontrados se moverán.",
        security_logic: "Lógica de Seguridad:",
        security_desc: "Las coordenadas secretas se guardan en archivos PHP protegidos.",

        branding: "Personalización",
        group_general: "Configuración General y de Página",
        branding_lang_select: "Seleccionar Idioma del Contenido:",
        lang_it: "Italiano",
        lang_en: "Inglés",
        lang_es: "Español",
        group_welcome: "Ventana de Bienvenida",
        group_vision: "Ventana de Misión",
        group_wordcloud: "Muro de la Fama (Nube de Palabras)",
        group_pricing: "Ventana de Precios / Información",
        wall_title_label: "Título de la Página (Navegador)",
        welcome_title_label: "Título de Bienvenida",
        welcome_text_label: "Intro de Bienvenida",
        welcome_details_label: "Detalles de Bienvenida (HTML Habilitado)",
        welcome_upload_label: "Info de Carga (Bienvenida)",
        support_email_label: "Email de Soporte",
        vision_title_label: "Título de la Misión",
        vision_text_label: "Texto de la Misión",
        vision_details_label: "Detalles Extra (HTML)",
        vision_image_label: "URL de Imagen de la Misión",
        vision_map_url_label: "URL del Mapa (Enlace)",
        vision_map_text_label: "Texto del Botón de Mapa",
        vision_tourism_url_label: "URL de Turismo (Enlace)",
        vision_tourism_text_label: "Texto del Botón de Turismo",
        wordcloud_title_label: "Título de la Nube de Palabras",
        wordcloud_text_label: "Descripción de la Nube de Palabras",
        pricing_email_text_label: "Texto del Email de Precios",
        group_style: "Estilo Global y Apariencia",
        modal_bg_color: "Color de Fondo de los Modales",
        modal_text_color: "Color de Texto de los Modales",
        modal_border_color: "Color de Borde de los Modales",
        modal_radius: "Radio del Borde de los Modales",
        modal_opacity: "Opacidad del Fondo de los Modales",
        btn_primary_bg: "Fondo del Botón Primario",
        btn_primary_text: "Texto del Botón Primario",
        box_vision_bg: "Fondo de la Caja de 'Misión'",
        box_wall_bg: "Fondo de la Caja de 'Muro de la Fama'",
        style_title_colors: "Gradiente del Título del Muro (4 Colores)",
        save_branding: "Guardar Personalización",
        branding_saved: "¡Personalización guardada con éxito!",
        title_placeholder: "ej. Actualización del Servidor",
        content_placeholder: "Escribe aquí... Usa <a> para enlaces.",
        cancel: "Cancelar",

        stripe_config_title: "Configuración de Stripe (Pagos)",
        stripe_pk_label: "Llave Publicable (pk_...)",
        stripe_sk_label: "Llave Secreta (sk_...)",
        stripe_wh_label: "Secreto de Webhook (whsec_...)",
        stripe_save: "Guardar Llaves de Stripe",
        stripe_saved: "Llaves de Stripe actualizadas con éxito.",
        stripe_warning: "ADVERTENCIA: Estas llaves son críticas. No las compartas nunca."
    }
};

let currentLang = localStorage.getItem('admin_lang') || 'it';

function t(key) {
    if (!adminTranslations[currentLang]) return key;
    return adminTranslations[currentLang][key] || key;
}

function setLanguage(lang) {
    currentLang = lang;
    localStorage.setItem('admin_lang', lang);
    updateInterface();
    // Reload dynamic forms by re-triggering their load function if available
    if (typeof loadSettings === 'function') loadSettings();
    if (typeof loadStats === 'function') loadStats();
    if (typeof loadWinners === 'function') loadWinners();
    if (typeof loadBranding === 'function') loadBranding();

    // Propagate to iframes
    document.querySelectorAll('iframe').forEach(frm => {
        try {
            if (frm.contentWindow && typeof frm.contentWindow.setLanguage === 'function') {
                if (frm.contentWindow.currentLang !== lang) {
                    frm.contentWindow.setLanguage(lang);
                }
            }
        } catch (e) { }
    });
}

function updateInterface() {
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        const val = t(key);
        if (el.hasAttribute('data-i18n-html')) {
            el.innerHTML = val;
        } else {
            el.innerText = val;
        }
    });

    // Handle Placeholders
    document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
        const key = el.getAttribute('data-i18n-placeholder');
        el.placeholder = t(key);
    });

    // Update active lang button state if exists
    document.querySelectorAll('.lang-btn').forEach(btn => {
        // Simple toggle class based on data-lang
        if (btn.dataset.lang === currentLang) {
            btn.style.opacity = '1';
            btn.style.transform = 'scale(1.1)';
        } else {
            btn.style.opacity = '0.5';
            btn.style.transform = 'scale(1)';
        }
    });
}

document.addEventListener('DOMContentLoaded', () => {
    updateInterface();
});
